### ISSUE TITLE
Completely remove a Boolean attribute?

### ISSUE THREAD

**Issue by mmortal03** [kjarmicki/attributes-replacer#2]
Is there a way to have this completely remove a Boolean attribute if present?

For instance, CNN videos have started to annoyingly turn on the closed captions by default. Their web designer is using the "<track> default" Boolean attribute to accomplish this. This "default" attribute has no value to replace -- it's either there, inside the track tag, or it's not. What I want to do is to have this check If it's present inside a track tag, and, if so, remove it.

See here for an example video with this issue: http://www.cnn.com/videos/us/2016/06/18/mountain-lion-attack-boy-colorado-newday.cnn

**Comment by kjarmicki** [comment]
Hi,

Unfortunately there is no way to delete an attribute at the moment, just to change it's contents.
But I went to CNN and haven't experienced your issue. Closed captions were off by default, when I turned them on they were kept on for other videos, but as soon as I turned them off, they stopped showing up. I agree that turning them on by default would be very annoying, therefore I think it's unlikely that CNN went for that.
Try to open this page in incognito mode - then if captions are off it's likely a user data issue and you should clear your cookies and localStorage

**Comment by mmortal03** [comment]
Thanks for the quick response. Yeah, the captions being on is also the default for me in incognito mode, and I have no extensions allowed there. Btw, I'm on Chrome version 52.0.2743.41 beta-m (64-bit), so, maybe it's just something with the Chrome beta branch? I guess I'll have to go test this out on a fresh machine and see if I can reproduce it there, and then start the process of elimination with my cookies. 
But more to the topic of your extension, I actually figured out a hack using it to just break captions completely as a workaround, by replacing the kind attribute in the track tag with "x" whenever it contains the word "captions". Not a perfect solution, but at least it makes things less annoying the majority of the time! Thanks again!

**Comment by kjarmicki** [comment]
Ok, cool :) Just for the record, I'm on Chrome stable 51.0.2704.103 (64-bit) @ Linux. 
I'm closing this one then, if somebody else shows up with similar issue I'll consider adding option to remove/modify an attribute itself.
