### ISSUE TITLE
Make replacing persistent across tabs

### ISSUE THREAD

**Issue by kjarmicki** [kjarmicki/attributes-replacer#3]
As mentioned in #1 

Scenario:
1. turn replacing on
2. switch to a different tab
3. contents of that page should be replaced according to the rules

Also: when replacing it turned off, changed should be reverted on all the tabs, not just active one.

**Comment by mmortal03** [comment]
The only complicating thing about this is that some people might actually *want* the setting to only be applied on a per tab basis. Given that I doubt there's code behind the scenes to handle things on a per tab basis, it might be reasonable to have this apply to all tabs for now, and later add per tab capabilities?

**Comment by kjarmicki** [comment]
Hm.. it shouldn't be much of a problem to add checkbox "apply to current tab only", but for now I'll go with replacing for all tabs. I've noticed that couple of other extensions I have installed behave that way (FoxyProxy, ModifyHeaders etc.) so for end users that's probably expected behavior.

**Comment by kjarmicki** [comment]
Hey @mmortal03 version 1.2.0 should be in Chrome Webstore now, please update your extension and tell me if it behaves as you'd expect (you might need to restart your browser after update).

**Comment by mmortal03** [comment]
I tested it a few different ways and it looks like it works. :) I'll let you know if I notice anything off.

**Comment by kjarmicki** [comment]
Cool :) If you spot anything weird that could be related to this change, please reopen this issue.
