### ISSUE TITLE
Targeting an iframe inside facebook

### ISSUE THREAD

**Issue by mlazkani** [kjarmicki/attributes-replacer#4]
Facebook Apps load inside an iframe within facebook, but this script doesn't seem to work for elements in that iframe? Thoughts?

**Comment by kjarmicki** [comment]
Hi,

Yes, it seems reasonable that if extension is `on` then it should run not only across all tabs, but inside of all iframes as well. From a brief research it seems possible to do, so expect a new version with that feature soon-ish :)

**Comment by kjarmicki** [comment]
@mlazkani version 1.2.1 which affects all the iframes on the page should now be in Chrome Web Store

**Comment by mlazkani** [comment]
Thank You, seems to work better now!
