### ISSUE TITLE
Having trouble understanding how to replace/wrap a link with another link but keep specific parts

### ISSUE THREAD

**Issue by keithmackey** [kjarmicki/attributes-replacer#6]
Hey there, I'm trying to figure out how to use this to keep a specific unknown string and having some difficulty. I don't really understand regular expressions well though so forgive me if this is quite simple/easy.

I'm trying to take a link

https;//www.replacethis.com/page/thisstringcouldbeanything or
https;//www.replacethis.com/page/thisstringcouldbeanything/randomtextetc

I would like to keep only thisstringcouldbeanything

and then add it into the middle of another url

https://www.newurl.com/("thisstringcouldbeanything"}

for the first simple part, I am basically to here, but not sure what to add to add characters to the end after it keeps the thisstringcouldbeanything

https;//www.replacethis.com/page/ => https://www.newurl.com/("

Thanks! Sorry if this is super basic.

**Comment by kjarmicki** [comment]
Hi!

I think what you're looking for are capturing groups and back-references. You can match a portion of a string in a group with parenthesis and then reference that match using a dollar sign.

If I understand your case correctly, this should be something like:
```
https://www.replacethis.com/page/([a-z]+) => https://www.newurl.com/$1
```

You can read more about them here: https://www.rexegg.com/regex-capture.html
