### ISSUE TITLE
Add in-line style to elements

### ISSUE THREAD

**Issue by alfredo-f** [kjarmicki/attributes-replacer#7]
# Objective
I would like to add in-line style to elements.

# Example 
I am trying to force a width of `50%` onto all `div[class~="example"]` at [this webpage](https://www.w3.org/TR/CSS21/selector.html)

![image](https://user-images.githubusercontent.com/22865959/163581524-38871b71-fe84-49a1-95f3-6da434c695e7.png)

# What I tried
The following doesn't work probably because the elements `div[class~="example"]` don't have the attribute `style` to begin with.

```
Attribute rewrite rules:
.* => "width: 50%"

Apply to selectors:
div[class="example"][style]
```

**Comment by kjarmicki** [comment]
Hello,

Sorry for the late reply, I just noticed your post. Unfortunately, as you correctly observed, my extension doesn't support the case where attributes are not present. I think the [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) extension could be what you're looking for.
